services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sulama_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres123@db:5432/sulama_db
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
          memory: 1g

  frontend:
    build:
      context: ./gsp-frontend
    working_dir: /app
    volumes:
      - ./gsp-frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - web
    deploy:
      resources:
        limits:
          memory: 2g

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
