services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: sulama_user
      POSTGRES_PASSWORD: Ardahan91185
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-tambis
    environment:
      PGADMIN_DEFAULT_EMAIL: info@uisoft.tech
      PGADMIN_DEFAULT_PASSWORD: ardahan91185
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

  web:
    build: .
    command: gunicorn sulama_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./gsp-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${FRONTEND_API_URL}
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "60:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
      - frontend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  

networks:
  app-network:
    driver: bridge 