# Generated by Django 4.2.7 on 2025-07-17 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sulama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('unvan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünvan')),
                ('departman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departman')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='KullaniciSulamaYetkisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetki_seviyesi', models.CharField(choices=[('SADECE_OKUMA', 'Sadece Okuma'), ('VERI_GIRISI', 'Veri Girişi'), ('YONETICI', 'Yönetici'), ('SUPER_YONETICI', 'Süper Yönetici')], default='SADECE_OKUMA', max_length=20, verbose_name='Yetki Seviyesi')),
                ('baslangic_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kullanici_profili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_sulama_yetkileri', to='authentication.kullaniciprofili', verbose_name='Kullanıcı Profili')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_yetkiler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('sulama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_yetkileri', to='sulama.sulama', verbose_name='Sulama Sistemi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Sulama Yetkisi',
                'verbose_name_plural': 'Kullanıcı Sulama Yetkileri',
                'ordering': ['kullanici_profili__user__username', 'sulama__isim'],
                'unique_together': {('kullanici_profili', 'sulama')},
            },
        ),
        migrations.AddField(
            model_name='kullaniciprofili',
            name='sulama_sistemleri',
            field=models.ManyToManyField(blank=True, through='authentication.KullaniciSulamaYetkisi', to='sulama.sulama', verbose_name='Sulama Sistemleri'),
        ),
        migrations.AddField(
            model_name='kullaniciprofili',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='GirisKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Giriş Tarihi')),
                ('ip_adresi', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(verbose_name='Tarayıcı Bilgisi')),
                ('basarili', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('hata_mesaji', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Giriş Kaydı',
                'verbose_name_plural': 'Giriş Kayıtları',
                'ordering': ['-giris_tarihi'],
            },
        ),
    ]
