# Generated by Django 4.2.7 on 2025-07-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolge',
            options={'ordering': ['isim'], 'verbose_name': 'Sulama Birliği', 'verbose_name_plural': 'Sulama Birlikleri'},
        ),
        migrations.AlterModelOptions(
            name='depolamatesisi',
            options={'ordering': ['isim'], 'verbose_name': 'Depolama Tesisi', 'verbose_name_plural': 'Depolama Tesisleri'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ['sulama__isim', 'isim'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='yillikgenelsutuketimi',
            options={'ordering': ['-yil', 'sulama__isim'], 'verbose_name': 'Yıllık Genel Su Tüketimi', 'verbose_name_plural': 'Yıllık Genel Su Tüketimi'},
        ),
        migrations.AlterField(
            model_name='urun',
            name='sulama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='sulama.bolge', verbose_name='Sulama Adi'),
        ),
    ]
