# Generated by Django 4.2.7 on 2025-07-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0002_alter_bolge_options_alter_depolamatesisi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolge',
            options={'ordering': ['isim'], 'verbose_name': 'Birlik', 'verbose_name_plural': 'Birlikler'},
        ),
        migrations.AlterModelOptions(
            name='depolamatesisi',
            options={'ordering': ['sulama__bolge__isim', 'isim'], 'verbose_name': 'Depolama Tesisi', 'verbose_name_plural': 'Depolama Tesisleri'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ['sulama__bolge__isim', 'sulama__isim', 'isim'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='yillikgenelsutuketimi',
            options={'ordering': ['-yil', 'sulama__bolge__isim', 'sulama__isim'], 'verbose_name': 'Yıllık Genel Su Tüketimi', 'verbose_name_plural': 'Yıllık Genel Su Tüketimi'},
        ),
        migrations.AlterModelOptions(
            name='yillikurundetay',
            options={'ordering': ['yillik_tuketim__yil', '-ekim_orani', 'urun__isim'], 'verbose_name': 'Yıllık Ürün Detayı', 'verbose_name_plural': 'Yıllık Ürün Detayları'},
        ),
        migrations.AlterField(
            model_name='gunluksebekeyealinansumiktari',
            name='yukseklik',
            field=models.FloatField(blank=True, null=True, verbose_name='Yükseklik (m)'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='sulama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='sulama.sulama', verbose_name='Sulama Adi'),
        ),
    ]
