# Generated by Django 4.2.7 on 2025-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0006_remove_makinakonum_hiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makina',
            name='birlik_no',
            field=models.CharField(blank=True, help_text='Makina için benzersiz birlik numarası', max_length=50, null=True, unique=True, verbose_name='Birlik No'),
        ),
    ]
