# Generated by Django 4.2.7 on 2025-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0007_add_birlik_no_to_makina'),
    ]

    operations = [
        migrations.AddField(
            model_name='makinais',
            name='calistigi_yer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Çalıştığı Yer'),
        ),
        migrations.AlterField(
            model_name='makinais',
            name='baslangic_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Zamanı'),
        ),
    ]
