# Generated by Django 4.2.7 on 2025-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0008_makinais_calistigi_yer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makina',
            name='birlik_no',
            field=models.CharField(default=1, help_text='Makina için benzersiz birlik numarası', max_length=50, unique=True, verbose_name='Birlik No'),
            preserve_default=False,
        ),
    ]
