# Generated by Django 4.2.7 on 2025-07-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0003_alter_bolge_options_alter_depolamatesisi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Makina Adı')),
                ('makina_tipi', models.CharField(choices=[('traktor', 'Traktör'), ('ekskavator', 'Ekskavatör'), ('buldozer', 'Buldozer'), ('yukleyici', 'Yükleyici'), ('diger', 'Diğer')], max_length=20, verbose_name='Makina Tipi')),
                ('plaka', models.CharField(blank=True, max_length=20, null=True, verbose_name='Plaka')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
                ('yil', models.IntegerField(blank=True, null=True, verbose_name='Üretim Yılı')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('bakim', 'Bakımda'), ('ariza', 'Arızalı')], default='aktif', max_length=10, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('sulama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makinalar', to='sulama.sulama', verbose_name='Sulama Sistemi')),
            ],
            options={
                'verbose_name': 'Makina',
                'verbose_name_plural': 'Makinalar',
                'ordering': ['sulama__bolge__isim', 'sulama__isim', 'isim'],
            },
        ),
        migrations.CreateModel(
            name='MakinaKonum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlem', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('boylam', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('hiz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hız (km/h)')),
                ('yon', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yön (derece)')),
                ('yakit_seviyesi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yakıt Seviyesi (%)')),
                ('motor_calisma', models.BooleanField(default=True, verbose_name='Motor Çalışıyor')),
                ('kayit_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
                ('makina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konumlar', to='sulama.makina', verbose_name='Makina')),
            ],
            options={
                'verbose_name': 'Makina Konumu',
                'verbose_name_plural': 'Makina Konumları',
                'ordering': ['-kayit_zamani'],
            },
        ),
        migrations.CreateModel(
            name='MakinaIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tipi', models.CharField(choices=[('sulama', 'Sulama'), ('bakim', 'Bakım'), ('tamir', 'Tamir'), ('tasima', 'Taşıma'), ('kazma', 'Kazma'), ('diger', 'Diğer')], max_length=20, verbose_name='İş Tipi')),
                ('baslik', models.CharField(max_length=200, verbose_name='İş Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='İş Açıklaması')),
                ('baslangic_zamani', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('bitis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandı'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='planlandi', max_length=20, verbose_name='Durum')),
                ('enlem', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='İş Yeri Enlem')),
                ('boylam', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='İş Yeri Boylam')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('makina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isler', to='sulama.makina', verbose_name='Makina')),
            ],
            options={
                'verbose_name': 'Makina İşi',
                'verbose_name_plural': 'Makina İşleri',
                'ordering': ['-baslangic_zamani'],
            },
        ),
    ]
