# Generated by Django 4.2.7 on 2025-07-31 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0004_makina_makinakonum_makinais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makina',
            name='sulama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makinalar', to='sulama.sulama', verbose_name='Sulama Sistemi'),
        ),
    ]
