# Generated by Django 4.2.7 on 2025-08-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0005_alter_makina_sulama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makinakonum',
            name='hiz',
        ),
        migrations.RemoveField(
            model_name='makinakonum',
            name='motor_calisma',
        ),
        migrations.RemoveField(
            model_name='makinakonum',
            name='yakit_seviyesi',
        ),
        migrations.RemoveField(
            model_name='makinakonum',
            name='yon',
        ),
    ]
